steps:
  - name: 'hemanthkopalle/terraform:bh1'
    args:
      - '-c'
      - |
        cd ${_DIR}
        terraform init -backend-config=${_BACKEND_CONFIG}
    id: terraform init
    entrypoint: sh
  - name: 'hemanthkopalle/terraform:bh1'
    args:
      - '-c'
      - |
        cd ${_DIR}
        terraform apply -var-file=${_TF_VARS} -auto-approve
    id: terraform apply
    entrypoint: sh
timeout: 86400s
