project_id               = "gke-svc-prj"
cluster_name  = "gke-autopilot-primary"
network_name             = "gke-poc-vpc"
subnet_name              = "gke-poc-east1"
network_project_id       = "gke-host-prj"
pods_range_name          = "ip-range-pods-autopilot"
svc_range_name           = "ip-range-svc-autopilot"
region                   = "us-east1"
master_ipv4_cidr_block   = "192.168.0.0/20" #For Master Cluster
initial_node_count = 1
